### ISSUE TITLE
Exception: This database was initialized with network_id 1 and can not be used when connecting to network_id 1337

### ISSUE THREAD

**Issue by ChihChengLiang** [konradkonrad/docker-pyeth-cluster#6]
Encounter this error when trying to mine. `docker run -it --rm --link bootstrap:bootstrap -v /tmp/pyethapp:/root/.config ethereum/client-python -c eth.network_id=1337 -b 'enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@bootstrap:30303' -m 50 run --fake`

```
INFO:accounts   searching for key files directory=/root/.config/pyethapp/keystore
INFO:accounts   found account(s) accounts=[<Account(address=222985029f2bab1e31a251f02e9c6f0cd206bb04, id=None)>, <Account(address=4689a81eeff9f84e930814b40fdbc936b41c86dc, id=None)>]
INFO:app        registering service service=accounts
INFO:db opening LevelDB path=/root/.config/pyethapp/leveldb max_open_files=128 block_cache_size=8388608 write_buffer_size=4194304
INFO:app        registering service service=db
INFO:p2p.discovery      NodeDiscovery init 
INFO:p2p.discovery      starting discovery proto this_enode=enode://ac2b823a713e4a323849123dea68dd7891647d3d78fc14f28971a5c5fe1f29abf9ed0ffdfd3abef582f5ca98107c3fda89e8931210bfa348c182ab504a39e2ba@0.0.0.0:30303
INFO:app        registering service service=discovery
INFO:p2p.peermgr        PeerManager init 
INFO:app        registering service service=peermanager
Traceback (most recent call last):
  File "/usr/local/bin/pyethapp", line 9, in <module>
    load_entry_point('pyethapp==1.0.3', 'console_scripts', 'pyethapp')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/pyrlp/pydevp2p/pyethereum/pyethapp/pyethapp/app.py", line 189, in run
    service.register_with_app(app)
  File "/pyrlp/pydevp2p/devp2p/service.py", line 46, in register_with_app
    s = klass(app)
  File "/pyrlp/pydevp2p/pyethereum/pyethapp/pyethapp/eth_service.py", line 131, in __init__
    db_network_id, sce['network_id'])
Exception: This database was initialized with network_id 1 and can not be used when connecting to network_id 1337
```

**Comment by konradkonrad** [comment]
@ChihChengLiang please let me know if https://github.com/konradkonrad/docker-pyeth-cluster/issues/5#issuecomment-223542335 solves this for you?

**Comment by ChihChengLiang** [comment]
works like a charm :)
